/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/app.server-module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/common';
import * as import4 from '@angular/router';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/platform-browser/animations';
import * as import7 from '@angular/platform-server';
import * as import8 from '@angular/forms';
import * as import9 from '../../../app/app-routing.module';
import * as import10 from '../../../app/app.module';
import * as import11 from '@angular/animations/browser';
import * as import12 from './home/home.component.ngfactory';
import * as import13 from './page2/page2.component.ngfactory';
import * as import14 from './app.component.ngfactory';
import * as import15 from '../../../app/home/home.component';
import * as import16 from '../../../app/page2/page2.component';
class AppServerModuleInjector extends import0.ɵNgModuleInjector<import1.AppServerModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ErrorHandler_2:any;
  _NgProbeToken_3:any[];
  _ɵg_4:import4.ɵg;
  _APP_ID_5:any;
  _ɵTRANSITION_ID_6:any;
  _APP_INITIALIZER_7:any[];
  _ApplicationInitStatus_8:import0.ApplicationInitStatus;
  _ɵf_9:import0.ɵf;
  _ApplicationRef_10:any;
  _ApplicationModule_11:import0.ApplicationModule;
  _BrowserModule_12:import5.BrowserModule;
  _NoopAnimationsModule_13:import6.NoopAnimationsModule;
  _ServerModule_14:import7.ServerModule;
  _ɵba_15:import8.ɵba;
  _FormsModule_16:import8.FormsModule;
  _ɵa_17:any;
  _UrlSerializer_18:import4.DefaultUrlSerializer;
  _RouterOutletMap_19:import4.RouterOutletMap;
  _APP_BASE_HREF_20:any;
  _ROUTER_CONFIGURATION_21:any;
  _LocationStrategy_22:any;
  _Location_23:import3.Location;
  _Compiler_24:import0.Compiler;
  _NgModuleFactoryLoader_25:import0.SystemJsNgModuleLoader;
  _ROUTES_26:any[];
  _Router_27:any;
  _RouterModule_28:import4.RouterModule;
  _AppRoutingModule_29:import9.AppRoutingModule;
  _AppModule_30:import10.AppModule;
  _AppServerModule_31:import1.AppServerModule;
  __BrowserXhr_32:import7.ɵc;
  __ResponseOptions_33:import2.BaseResponseOptions;
  __XSRFStrategy_34:import7.ɵd;
  __XHRBackend_35:import2.XHRBackend;
  __RequestOptions_36:import2.BaseRequestOptions;
  __Http_37:any;
  __LOCALE_ID_38:any;
  __NgLocalization_39:import3.NgLocaleLocalization;
  __IterableDiffers_40:any;
  __KeyValueDiffers_41:any;
  __DomSanitizer_42:import5.ɵe;
  __Sanitizer_43:any;
  __HAMMER_GESTURE_CONFIG_44:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_45:any[];
  __EventManager_46:import5.EventManager;
  __ɵDomSharedStylesHost_47:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_48:import5.ɵDomRendererFactory2;
  __ɵb_49:import7.ɵb;
  __ɵSharedStylesHost_50:any;
  __ɵServerRendererFactory2_51:import7.ɵServerRendererFactory2;
  __ɵAnimationEngine_52:import11.ɵNoopAnimationEngine;
  __RendererFactory2_53:any;
  __Testability_54:any;
  __Meta_55:import5.Meta;
  __Title_56:import5.Title;
  __ɵi_57:import8.ɵi;
  __ActivatedRoute_58:any;
  __NoPreloading_59:import4.NoPreloading;
  __PreloadingStrategy_60:any;
  __RouterPreloader_61:import4.RouterPreloader;
  __PreloadAllModules_62:import4.PreloadAllModules;
  __ROUTER_INITIALIZER_63:any;
  __APP_BOOTSTRAP_LISTENER_64:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import12.HomeComponentNgFactory,
      import13.Page2ComponentNgFactory,
      import14.AppComponentNgFactory
    ]
    ,[import14.AppComponentNgFactory]);
  }
  get _BrowserXhr_32():import7.ɵc {
    if ((this.__BrowserXhr_32 == null)) { (this.__BrowserXhr_32 = new import7.ɵc()); }
    return this.__BrowserXhr_32;
  }
  get _ResponseOptions_33():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_33 == null)) { (this.__ResponseOptions_33 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_33;
  }
  get _XSRFStrategy_34():import7.ɵd {
    if ((this.__XSRFStrategy_34 == null)) { (this.__XSRFStrategy_34 = new import7.ɵd()); }
    return this.__XSRFStrategy_34;
  }
  get _XHRBackend_35():import2.XHRBackend {
    if ((this.__XHRBackend_35 == null)) { (this.__XHRBackend_35 = new import2.XHRBackend(this._BrowserXhr_32,this._ResponseOptions_33,this._XSRFStrategy_34)); }
    return this.__XHRBackend_35;
  }
  get _RequestOptions_36():import2.BaseRequestOptions {
    if ((this.__RequestOptions_36 == null)) { (this.__RequestOptions_36 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_36;
  }
  get _Http_37():any {
    if ((this.__Http_37 == null)) { (this.__Http_37 = import7.ɵe(this._XHRBackend_35,this._RequestOptions_36)); }
    return this.__Http_37;
  }
  get _LOCALE_ID_38():any {
    if ((this.__LOCALE_ID_38 == null)) { (this.__LOCALE_ID_38 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_38;
  }
  get _NgLocalization_39():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_39 == null)) { (this.__NgLocalization_39 = new import3.NgLocaleLocalization(this._LOCALE_ID_38)); }
    return this.__NgLocalization_39;
  }
  get _IterableDiffers_40():any {
    if ((this.__IterableDiffers_40 == null)) { (this.__IterableDiffers_40 = import0.ɵl()); }
    return this.__IterableDiffers_40;
  }
  get _KeyValueDiffers_41():any {
    if ((this.__KeyValueDiffers_41 == null)) { (this.__KeyValueDiffers_41 = import0.ɵm()); }
    return this.__KeyValueDiffers_41;
  }
  get _DomSanitizer_42():import5.ɵe {
    if ((this.__DomSanitizer_42 == null)) { (this.__DomSanitizer_42 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_42;
  }
  get _Sanitizer_43():any {
    if ((this.__Sanitizer_43 == null)) { (this.__Sanitizer_43 = this._DomSanitizer_42); }
    return this.__Sanitizer_43;
  }
  get _HAMMER_GESTURE_CONFIG_44():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_44 == null)) { (this.__HAMMER_GESTURE_CONFIG_44 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_44;
  }
  get _EVENT_MANAGER_PLUGINS_45():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_45 == null)) { (this.__EVENT_MANAGER_PLUGINS_45 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_44)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_45;
  }
  get _EventManager_46():import5.EventManager {
    if ((this.__EventManager_46 == null)) { (this.__EventManager_46 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_45,this.parent.get(import0.NgZone))); }
    return this.__EventManager_46;
  }
  get _ɵDomSharedStylesHost_47():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_47 == null)) { (this.__ɵDomSharedStylesHost_47 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_47;
  }
  get _ɵDomRendererFactory2_48():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_48 == null)) { (this.__ɵDomRendererFactory2_48 = new import5.ɵDomRendererFactory2(this._EventManager_46,this._ɵDomSharedStylesHost_47)); }
    return this.__ɵDomRendererFactory2_48;
  }
  get _ɵb_49():import7.ɵb {
    if ((this.__ɵb_49 == null)) { (this.__ɵb_49 = new import7.ɵb(this.parent.get(import5.DOCUMENT),this._ɵTRANSITION_ID_6)); }
    return this.__ɵb_49;
  }
  get _ɵSharedStylesHost_50():any {
    if ((this.__ɵSharedStylesHost_50 == null)) { (this.__ɵSharedStylesHost_50 = this._ɵb_49); }
    return this.__ɵSharedStylesHost_50;
  }
  get _ɵServerRendererFactory2_51():import7.ɵServerRendererFactory2 {
    if ((this.__ɵServerRendererFactory2_51 == null)) { (this.__ɵServerRendererFactory2_51 = new import7.ɵServerRendererFactory2(this.parent.get(import0.NgZone),this.parent.get(import5.DOCUMENT),this._ɵSharedStylesHost_50)); }
    return this.__ɵServerRendererFactory2_51;
  }
  get _ɵAnimationEngine_52():import11.ɵNoopAnimationEngine {
    if ((this.__ɵAnimationEngine_52 == null)) { (this.__ɵAnimationEngine_52 = new import11.ɵNoopAnimationEngine()); }
    return this.__ɵAnimationEngine_52;
  }
  get _RendererFactory2_53():any {
    if ((this.__RendererFactory2_53 == null)) { (this.__RendererFactory2_53 = import7.ɵa(this._ɵServerRendererFactory2_51,this._ɵAnimationEngine_52,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_53;
  }
  get _Testability_54():any {
    if ((this.__Testability_54 == null)) { (this.__Testability_54 = (null as any)); }
    return this.__Testability_54;
  }
  get _Meta_55():import5.Meta {
    if ((this.__Meta_55 == null)) { (this.__Meta_55 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_55;
  }
  get _Title_56():import5.Title {
    if ((this.__Title_56 == null)) { (this.__Title_56 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_56;
  }
  get _ɵi_57():import8.ɵi {
    if ((this.__ɵi_57 == null)) { (this.__ɵi_57 = new import8.ɵi()); }
    return this.__ɵi_57;
  }
  get _ActivatedRoute_58():any {
    if ((this.__ActivatedRoute_58 == null)) { (this.__ActivatedRoute_58 = import4.ɵf(this._Router_27)); }
    return this.__ActivatedRoute_58;
  }
  get _NoPreloading_59():import4.NoPreloading {
    if ((this.__NoPreloading_59 == null)) { (this.__NoPreloading_59 = new import4.NoPreloading()); }
    return this.__NoPreloading_59;
  }
  get _PreloadingStrategy_60():any {
    if ((this.__PreloadingStrategy_60 == null)) { (this.__PreloadingStrategy_60 = this._NoPreloading_59); }
    return this.__PreloadingStrategy_60;
  }
  get _RouterPreloader_61():import4.RouterPreloader {
    if ((this.__RouterPreloader_61 == null)) { (this.__RouterPreloader_61 = new import4.RouterPreloader(this._Router_27,this._NgModuleFactoryLoader_25,this._Compiler_24,this,this._PreloadingStrategy_60)); }
    return this.__RouterPreloader_61;
  }
  get _PreloadAllModules_62():import4.PreloadAllModules {
    if ((this.__PreloadAllModules_62 == null)) { (this.__PreloadAllModules_62 = new import4.PreloadAllModules()); }
    return this.__PreloadAllModules_62;
  }
  get _ROUTER_INITIALIZER_63():any {
    if ((this.__ROUTER_INITIALIZER_63 == null)) { (this.__ROUTER_INITIALIZER_63 = import4.ɵi(this._ɵg_4)); }
    return this.__ROUTER_INITIALIZER_63;
  }
  get _APP_BOOTSTRAP_LISTENER_64():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_64 == null)) { (this.__APP_BOOTSTRAP_LISTENER_64 = [this._ROUTER_INITIALIZER_63]); }
    return this.__APP_BOOTSTRAP_LISTENER_64;
  }
  createInternal():import1.AppServerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ErrorHandler_2 = import5.ɵa();
    this._NgProbeToken_3 = [import4.ɵb()];
    this._ɵg_4 = new import4.ɵg(this);
    this._APP_ID_5 = 'bclight';
    this._ɵTRANSITION_ID_6 = this._APP_ID_5;
    this._APP_INITIALIZER_7 = [
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3),
      import4.ɵh(this._ɵg_4),
      import5.ɵf(this._ɵTRANSITION_ID_6,this.parent.get(import5.DOCUMENT))
    ]
    ;
    this._ApplicationInitStatus_8 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_7);
    this._ɵf_9 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_8);
    this._ApplicationRef_10 = this._ɵf_9;
    this._ApplicationModule_11 = new import0.ApplicationModule(this._ApplicationRef_10);
    this._BrowserModule_12 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._NoopAnimationsModule_13 = new import6.NoopAnimationsModule();
    this._ServerModule_14 = new import7.ServerModule();
    this._ɵba_15 = new import8.ɵba();
    this._FormsModule_16 = new import8.FormsModule();
    this._ɵa_17 = import4.ɵd(this.parent.get(import4.Router,(null as any)));
    this._UrlSerializer_18 = new import4.DefaultUrlSerializer();
    this._RouterOutletMap_19 = new import4.RouterOutletMap();
    this._APP_BASE_HREF_20 = '/';
    this._ROUTER_CONFIGURATION_21 = {};
    this._LocationStrategy_22 = import4.ɵc(this.parent.get(import3.PlatformLocation),this._APP_BASE_HREF_20,this._ROUTER_CONFIGURATION_21);
    this._Location_23 = new import3.Location(this._LocationStrategy_22);
    this._Compiler_24 = new import0.Compiler();
    this._NgModuleFactoryLoader_25 = new import0.SystemJsNgModuleLoader(this._Compiler_24,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_26 = [[
        {
          path: '',
          component: import15.HomeComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'page2',
          component: import16.Page2Component
        }
        ,
        {
          path: 'main',
          loadChildren: './main/main.module#MainModule'
        }

      ]
    ];
    this._Router_27 = import4.ɵe(this._ApplicationRef_10,this._UrlSerializer_18,this._RouterOutletMap_19,this._Location_23,this,this._NgModuleFactoryLoader_25,this._Compiler_24,this._ROUTES_26,this._ROUTER_CONFIGURATION_21,this.parent.get(import4.UrlHandlingStrategy,(null as any)),this.parent.get(import4.RouteReuseStrategy,(null as any)));
    this._RouterModule_28 = new import4.RouterModule(this._ɵa_17,this._Router_27);
    this._AppRoutingModule_29 = new import9.AppRoutingModule();
    this._AppModule_30 = new import10.AppModule();
    this._AppServerModule_31 = new import1.AppServerModule();
    return this._AppServerModule_31;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import4.ɵg)) { return this._ɵg_4; }
    if ((token === import0.APP_ID)) { return this._APP_ID_5; }
    if ((token === import5.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_6; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_7; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_8; }
    if ((token === import0.ɵf)) { return this._ɵf_9; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_10; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_11; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_12; }
    if ((token === import6.NoopAnimationsModule)) { return this._NoopAnimationsModule_13; }
    if ((token === import7.ServerModule)) { return this._ServerModule_14; }
    if ((token === import8.ɵba)) { return this._ɵba_15; }
    if ((token === import8.FormsModule)) { return this._FormsModule_16; }
    if ((token === import4.ɵa)) { return this._ɵa_17; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_18; }
    if ((token === import4.RouterOutletMap)) { return this._RouterOutletMap_19; }
    if ((token === import3.APP_BASE_HREF)) { return this._APP_BASE_HREF_20; }
    if ((token === import4.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_21; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_22; }
    if ((token === import3.Location)) { return this._Location_23; }
    if ((token === import0.Compiler)) { return this._Compiler_24; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_25; }
    if ((token === import4.ROUTES)) { return this._ROUTES_26; }
    if ((token === import4.Router)) { return this._Router_27; }
    if ((token === import4.RouterModule)) { return this._RouterModule_28; }
    if ((token === import9.AppRoutingModule)) { return this._AppRoutingModule_29; }
    if ((token === import10.AppModule)) { return this._AppModule_30; }
    if ((token === import1.AppServerModule)) { return this._AppServerModule_31; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_32; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_33; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_34; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_35; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_36; }
    if ((token === import2.Http)) { return this._Http_37; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_38; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_39; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_40; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_41; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_42; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_43; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_44; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_45; }
    if ((token === import5.EventManager)) { return this._EventManager_46; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_47; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_48; }
    if ((token === import7.ɵb)) { return this._ɵb_49; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_50; }
    if ((token === import7.ɵServerRendererFactory2)) { return this._ɵServerRendererFactory2_51; }
    if ((token === import11.ɵAnimationEngine)) { return this._ɵAnimationEngine_52; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_53; }
    if ((token === import0.Testability)) { return this._Testability_54; }
    if ((token === import5.Meta)) { return this._Meta_55; }
    if ((token === import5.Title)) { return this._Title_56; }
    if ((token === import8.ɵi)) { return this._ɵi_57; }
    if ((token === import4.ActivatedRoute)) { return this._ActivatedRoute_58; }
    if ((token === import4.NoPreloading)) { return this._NoPreloading_59; }
    if ((token === import4.PreloadingStrategy)) { return this._PreloadingStrategy_60; }
    if ((token === import4.RouterPreloader)) { return this._RouterPreloader_61; }
    if ((token === import4.PreloadAllModules)) { return this._PreloadAllModules_62; }
    if ((token === import4.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_63; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_64; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_9.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_47 && this._ɵDomSharedStylesHost_47.ngOnDestroy());
    (this.__RouterPreloader_61 && this._RouterPreloader_61.ngOnDestroy());
  }
}
export const AppServerModuleNgFactory:import0.NgModuleFactory<import1.AppServerModule> = new import0.NgModuleFactory<any>(AppServerModuleInjector,import1.AppServerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvYXBwLnNlcnZlci1tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvYXBwLnNlcnZlci1tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
