/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './main.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../app/main/main.component';
const styles_MainComponent:any[] = [import0.styles];
export const RenderType_MainComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MainComponent,
  data: {}
}
);
export function View_MainComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  main works!\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_MainComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-main',([] as any[]),(null as any),(null as any),(null as any),View_MainComponent_0,RenderType_MainComponent)),
    import1.ɵdid(57344,(null as any),0,import2.MainComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MainComponentNgFactory:import1.ComponentFactory<import2.MainComponent> = import1.ɵccf('app-main',import2.MainComponent,View_MainComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvbWFpbi9tYWluLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2JjbGlnaHQvc3JjL2FwcC9tYWluL21haW4uY29tcG9uZW50LnRzIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvbWFpbi9tYWluLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvbWFpbi9tYWluLmNvbXBvbmVudC50cy5NYWluQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIG1haW4gd29ya3MhXG48L3A+XG4iLCI8YXBwLW1haW4+PC9hcHAtbWFpbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUc7SUFFQzs7Ozs7O0lDRko7Z0JBQUE7OztJQUFBOzs7In0=
