/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/main/main.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '../../../../app/main/main-routing.module';
import * as import5 from './main.component.ngfactory';
import * as import6 from '../../../../app/main/main.component';
class MainModuleInjector extends import0.ɵNgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _MainRoutingModule_2:import4.MainRoutingModule;
  _MainModule_3:import1.MainModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  _ROUTES_5:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import5.MainComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)),this.parent.get(import3.Router,(null as any)));
    this._MainRoutingModule_2 = new import4.MainRoutingModule();
    this._MainModule_3 = new import1.MainModule();
        this._ROUTES_5 = [[{
          path: '',
          component: import6.MainComponent,
          pathMatch: 'full'
        }
    ]];
    return this._MainModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.MainRoutingModule)) { return this._MainRoutingModule_2; }
    if ((token === import1.MainModule)) { return this._MainModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.ROUTES)) { return this._ROUTES_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory<any>(MainModuleInjector,import1.MainModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvbWFpbi9tYWluLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2JjbGlnaHQvc3JjL2FwcC9tYWluL21haW4ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
