/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './page2.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../app/page2/page2.component';
const styles_Page2Component:any[] = [import0.styles];
export const RenderType_Page2Component:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_Page2Component,
  data: {}
}
);
export function View_Page2Component_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  page2 works!\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_Page2Component_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-page2',([] as any[]),(null as any),(null as any),(null as any),View_Page2Component_0,RenderType_Page2Component)),
    import1.ɵdid(57344,(null as any),0,import2.Page2Component,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const Page2ComponentNgFactory:import1.ComponentFactory<import2.Page2Component> = import1.ɵccf('app-page2',import2.Page2Component,View_Page2Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvcGFnZTIvcGFnZTIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYmNsaWdodC9zcmMvYXBwL3BhZ2UyL3BhZ2UyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYmNsaWdodC9zcmMvYXBwL3BhZ2UyL3BhZ2UyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9iY2xpZ2h0L3NyYy9hcHAvcGFnZTIvcGFnZTIuY29tcG9uZW50LnRzLlBhZ2UyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHBhZ2UyIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1wYWdlMj48L2FwcC1wYWdlMj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUc7SUFFQzs7Ozs7O0lDRko7Z0JBQUE7OztJQUFBOzs7In0=
